"""Arizona permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'AZ'
    STATE_NAME = 'Arizona'
    SOURCES: list[dict[str, Any]] = [{'key': 'AZ_Phoenix_Permits',
      'name': 'Phoenix PDD Permits',
      'kind': 'unimplemented',
      'url': 'https://www.phoenix.gov/pdd/permits',
      'reason': 'Phoenix PlanIt portal — JS-rendered'},
     {'key': 'AZ_ADOT_Permits',
      'name': 'ADOT Encroachment Permits',
      'kind': 'unimplemented',
      'url': 'https://azdot.gov/business/engineering-and-construction/permits',
      'reason': 'ADOT permits via Permitting Portal — auth required'}]

