"""California permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'CA'
    STATE_NAME = 'California'
    SOURCES: list[dict[str, Any]] = [{'key': 'CA_LA_Building',
      'name': 'Los Angeles Building & Safety Permits',
      'kind': 'socrata',
      'domain': 'data.lacity.org',
      'dataset': 'nbyu-2ha9',
      'url': 'https://data.lacity.org/A-Prosperous-City/Building-and-Safety-Permit-Information/nbyu-2ha9',
      'issue_date_field': 'issue_date',
      'limit': 5000,
      'fields': {'permit_number': 'permit_nbr',
                 'applicant': 'contractor_s_business_name',
                 'address': 'address_start',
                 'permit_type': 'permit_type',
                 'issue_date': 'issue_date',
                 'filed_date': 'status_date',
                 'expiration_date': 'permit_expiration_date',
                 'description': 'permit_sub_type'}},
     {'key': 'CA_SF_Building',
      'name': 'San Francisco Building Permits',
      'kind': 'unimplemented',
      'url': 'https://data.sfgov.org/Housing-and-Buildings/Building-Permits/i98e-djp9',
      'reason': "Dataset i98e-djp9 has no contractor/applicant name fields. "
                "Use the SF DataSF Permits Application dataset (look for "
                "applicant_name) — search portal for current dataset id."},
     {'key': 'CA_SF_StreetUse',
      'name': 'San Francisco Street-Use Permits',
      'kind': 'unimplemented',
      'url': 'https://sfdpw.org/permits',
      'reason': "DPW street-use permits aren't on a Socrata dataset"},
     {'key': 'CA_Caltrans_Encroachment',
      'name': 'Caltrans Encroachment Permits',
      'kind': 'unimplemented',
      'url': 'https://encroachmentpermits.dot.ca.gov/',
      'reason': 'Caltrans EPMS portal — JS-rendered + captcha; needs Playwright + likely auth'}]

