"""Colorado permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'CO'
    STATE_NAME = 'Colorado'
    SOURCES: list[dict[str, Any]] = [{'key': 'CO_Denver_Permits',
      'name': 'Denver Building Permits',
      'kind': 'unimplemented',
      'url': 'https://opendata-geospatialdenver.hub.arcgis.com/',
      'reason': 'Denver publishes through ArcGIS Hub — needs FeatureServer URL'},
     {'key': 'CO_CDOT',
      'name': 'CDOT Access & Utility Permits',
      'kind': 'unimplemented',
      'url': 'https://www.codot.gov/business/permits',
      'reason': 'CDOT permits via OnBase portal — auth required'}]

