"""Florida permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'FL'
    STATE_NAME = 'Florida'
    SOURCES: list[dict[str, Any]] = [{'key': 'FL_Miami_Permits',
      'name': 'Miami-Dade Permits',
      'kind': 'unimplemented',
      'url': 'https://gis-mdc.opendata.arcgis.com/',
      'reason': 'Miami-Dade ArcGIS Hub — FeatureServer URL needs sniffing'},
     {'key': 'FL_FDOT_Permits',
      'name': 'FDOT Permits',
      'kind': 'unimplemented',
      'url': 'https://www.fdot.gov/permits/default.shtm',
      'reason': 'FDOT One-Stop Permitting — auth required'}]

