"""Georgia permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'GA'
    STATE_NAME = 'Georgia'
    SOURCES: list[dict[str, Any]] = [{'key': 'GA_Atlanta_Permits',
      'name': 'Atlanta Building Permits',
      'kind': 'unimplemented',
      'url': 'https://aurora.atlantaga.gov/',
      'reason': 'Aurora portal — JS-rendered, needs Playwright'},
     {'key': 'GA_GDOT_Permits',
      'name': 'GDOT Permits',
      'kind': 'unimplemented',
      'url': 'https://www.dot.ga.gov/PartnerSmart/Business/Pages/Permits.aspx',
      'reason': 'GDOT permits via GUPS — auth required'}]

