"""Illinois permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'IL'
    STATE_NAME = 'Illinois'
    SOURCES: list[dict[str, Any]] = [{'key': 'IL_Chicago_Building',
      'name': 'Chicago Building Permits',
      'kind': 'socrata',
      'domain': 'data.cityofchicago.org',
      'dataset': 'ydr8-5enu',
      'url': 'https://data.cityofchicago.org/Buildings/Building-Permits/ydr8-5enu',
      'issue_date_field': 'issue_date',
      'limit': 5000,
      # Only pull rows where at least one contact slot looks like a contractor.
      'relevant_filter': "upper(contact_1_type) like '%CONTRACTOR%' OR upper(contact_2_type) like '%CONTRACTOR%'",
      'fields': {'permit_number': 'permit_',
                 # `applicant` is reconstructed by the subclass below.
                 'applicant': '__merged_applicant',
                 'applicant_city': '__merged_applicant_city',
                 'applicant_state': '__merged_applicant_state',
                 'applicant_zip': '__merged_applicant_zip',
                 'address': 'street_number',
                 'permit_type': 'permit_type',
                 'issue_date': 'issue_date',
                 'filed_date': 'application_start_date',
                 'description': 'work_description'}},
     {'key': 'IL_IDOT',
      'name': 'IDOT Highway Permits',
      'kind': 'unimplemented',
      'url': 'https://idot.illinois.gov/transportation-system/local-transportation-partners/county-engineers-and-local-public-agencies/permits',
      'reason': 'IDOT permits filed via local district offices; no public listing'}]

    def _socrata_row_to_permit(self, row, source):
        # Chicago dataset has contact_1 and contact_2 — type tells us
        # which is the contractor. Pick the contractor-typed slot and
        # synthesize a single applicant view for the matcher.
        if source.get("dataset") == "ydr8-5enu":
            row = dict(row)
            picked = None
            for n in (1, 2):
                if "CONTRACTOR" in (row.get(f"contact_{n}_type") or "").upper():
                    picked = n
                    break
            row["__merged_applicant"]       = row.get(f"contact_{picked}_name", "") if picked else ""
            row["__merged_applicant_city"]  = row.get(f"contact_{picked}_city", "") if picked else ""
            row["__merged_applicant_state"] = row.get(f"contact_{picked}_state", "") if picked else ""
            row["__merged_applicant_zip"]   = row.get(f"contact_{picked}_zipcode", "") if picked else ""
        return super()._socrata_row_to_permit(row, source)

