"""Louisiana permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'LA'
    STATE_NAME = 'Louisiana'
    SOURCES: list[dict[str, Any]] = [{'key': 'LA_NewOrleans',
      'name': 'New Orleans Permits',
      'kind': 'unimplemented',
      'url': 'https://www.nola.gov/safety-and-permits/',
      'reason': 'needs scraper implementation — start by inspecting the linked portal'}]

