"""Massachusetts permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'MA'
    STATE_NAME = 'Massachusetts'
    SOURCES: list[dict[str, Any]] = [{'key': 'MA_Boston_Permits',
      'name': 'Boston ISD Approved Building Permits',
      'kind': 'unimplemented',
      'url': 'https://data.boston.gov/dataset/approved-building-permits',
      'reason': "Boston runs CKAN (not Socrata). Use api/3/action/datastore_search "
                "after looking up the current resource_id via "
                "https://data.boston.gov/api/3/action/package_show?id=approved-building-permits"}]

