"""North Carolina permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'NC'
    STATE_NAME = 'North Carolina'
    SOURCES: list[dict[str, Any]] = [{'key': 'NC_Charlotte_Permits',
      'name': 'Charlotte Building Permits',
      'kind': 'unimplemented',
      'url': 'https://data.charlottenc.gov/',
      'reason': 'Charlotte ArcGIS Hub — FeatureServer URL needs sniffing'},
     {'key': 'NC_Raleigh_Permits',
      'name': 'Raleigh Building Permits',
      'kind': 'unimplemented',
      'url': 'https://data.raleighnc.gov/',
      'reason': 'Raleigh ArcGIS Hub — FeatureServer URL needs sniffing'},
     {'key': 'NC_NCDOT_Permits',
      'name': 'NCDOT Encroachment Permits',
      'kind': 'unimplemented',
      'url': 'https://connect.ncdot.gov/business/Pages/Permits.aspx',
      'reason': 'NCDOT encroachment permits filed via PEPS — auth required'}]

