"""New York permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'NY'
    STATE_NAME = 'New York'
    SOURCES: list[dict[str, Any]] = [{'key': 'NY_NYC_DOB',
      'name': 'NYC DOB Permit Issuance',
      'kind': 'socrata',
      'domain': 'data.cityofnewyork.us',
      'dataset': 'ipu4-2q9a',
      'url': 'https://data.cityofnewyork.us/Housing-Development/DOB-Permit-Issuance/ipu4-2q9a',
      'issue_date_field': 'issuance_date',
      'limit': 5000,
      'fields': {'permit_number': 'job__',
                 'applicant': '__merged_applicant',
                 'applicant_phone': 'permittee_s_phone__',
                 'applicant_license': 'permittee_s_license__',
                 'applicant_license_type': 'permittee_s_license_type',
                 'address': 'house__',
                 'permit_type': 'permit_type',
                 'issue_date': 'issuance_date',
                 'filed_date': 'filing_date',
                 'expiration_date': 'expiration_date',
                 'description': 'work_type'}},
     {'key': 'NY_NYC_DOT_StreetWork',
      'name': 'NYC DOT Street Construction Permits',
      'kind': 'unimplemented',
      'url': 'https://www1.nyc.gov/html/dot/html/infrastructure/streetwork-permits.shtml',
      'reason': 'DOT Permit Search requires session token / form POST'},
     {'key': 'NY_State_DOT',
      'name': 'NYSDOT Highway Work Permits',
      'kind': 'unimplemented',
      'url': 'https://www.dot.ny.gov/main/business-center/engineering/specifications-engineering/work-permits',
      'reason': "NYSDOT permits aren't published as a public dataset"}]

    def _socrata_row_to_permit(self, row, source):
        # NYC DOB splits applicant across multiple fields; reconstruct.
        if source.get("dataset") == "ipu4-2q9a":
            biz = (row.get("permittee_s_business_name") or "").strip()
            first = (row.get("permittee_s_first_name") or "").strip()
            last  = (row.get("permittee_s_last_name") or "").strip()
            applicant = biz or " ".join(p for p in (first, last) if p)
            row = dict(row)
            row["__merged_applicant"] = applicant
        return super()._socrata_row_to_permit(row, source)

