"""Oregon permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'OR'
    STATE_NAME = 'Oregon'
    SOURCES: list[dict[str, Any]] = [{'key': 'OR_Portland_ROW',
      'name': 'Portland ROW Permits',
      'kind': 'unimplemented',
      'url': 'https://www.portland.gov/transportation/permitting',
      'reason': 'PBOT permits via Cityworks portal — auth required for full data'},
     {'key': 'OR_ODOT_Permits',
      'name': 'ODOT Permits',
      'kind': 'unimplemented',
      'url': 'https://www.oregon.gov/odot/Permits/',
      'reason': "ODOT ROW permits aren't published as a public dataset"}]

