"""Pennsylvania permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'PA'
    STATE_NAME = 'Pennsylvania'
    SOURCES: list[dict[str, Any]] = [{'key': 'PA_Philly_Permits',
      'name': 'Philadelphia L&I Building Permits',
      'kind': 'unimplemented',
      'url': 'https://www.opendataphilly.org/dataset/licenses-and-inspections-building-permits',
      'reason': 'Philadelphia L&I uses Carto, not Socrata — needs separate fetch impl'},
     {'key': 'PA_Pittsburgh_Permits',
      'name': 'Pittsburgh PLI Permits',
      'kind': 'unimplemented',
      'url': 'https://data.wprdc.org/dataset/pittsburgh-pli-permits-issued',
      'reason': 'WPRDC CKAN — needs separate fetch impl'},
     {'key': 'PA_PennDOT',
      'name': 'PennDOT Highway Occupancy Permits',
      'kind': 'unimplemented',
      'url': 'https://www.dot.state.pa.us/Public/PdfForms/Forms/M-945A.pdf',
      'reason': 'PennDOT HOPs filed via ePermitting — auth required'}]

