"""Rhode Island permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'RI'
    STATE_NAME = 'Rhode Island'
    SOURCES: list[dict[str, Any]] = [{'key': 'RI_Providence',
      'name': 'Providence Permits',
      'kind': 'unimplemented',
      'url': 'https://www.providenceri.gov/',
      'reason': 'needs scraper implementation — start by inspecting the linked portal'}]

