"""Texas permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'TX'
    STATE_NAME = 'Texas'
    SOURCES: list[dict[str, Any]] = [{'key': 'TX_Austin_Construction',
      'name': 'Austin Issued Construction Permits',
      'kind': 'unimplemented',
      'url': 'https://data.austintexas.gov/Building-and-Development/Issued-Construction-Permits/3syk-w9eu',
      'reason': "Dataset 3syk-w9eu omits contractor name. Use the contractor-trades "
                "dataset (e.g. uri7-hbbe Construction Permit – Contractor Trades) and "
                "join on permit_number, OR use TDLR's contractor license API."},
     {'key': 'TX_Houston_Permits',
      'name': 'Houston Public Works Permits',
      'kind': 'unimplemented',
      'url': 'https://www.houstonpermittingcenter.org/',
      'reason': 'Houston permits live behind ILMS — no public dataset'},
     {'key': 'TX_Dallas_Permits',
      'name': 'Dallas Building Permits',
      'kind': 'unimplemented',
      'url': 'https://www.dallasopendata.com/',
      'reason': 'Dataset ID needs verification — see DallasOpenData portal'},
     {'key': 'TX_TxDOT_ROW',
      'name': 'TxDOT Right-of-Way Permits',
      'kind': 'unimplemented',
      'url': 'https://www.txdot.gov/business/resources/right-of-way.html',
      'reason': "TxDOT ROW permits aren't published as a queryable dataset"}]

