"""Washington permit scraper.

This file was generated by `_gen_state_scrapers.py`. Edits made directly
will be overwritten if you re-run the generator. To customize per-state
behavior beyond the SOURCES list, override `fetch_one()` or
`_socrata_row_to_permit()` here.
"""
from __future__ import annotations

from typing import Any

from .base import BasePermitScraper


class Scraper(BasePermitScraper):
    STATE = 'WA'
    STATE_NAME = 'Washington'
    SOURCES: list[dict[str, Any]] = [{'key': 'WA_Seattle_Building',
      'name': 'Seattle SDCI Built-Environment Permits',
      'kind': 'socrata',
      'domain': 'data.seattle.gov',
      'dataset': '76t5-zqzr',
      'url': 'https://data.seattle.gov/Permitting/Built-Environment-Permits/76t5-zqzr',
      'issue_date_field': 'issueddate',
      'limit': 5000,
      'fields': {'permit_number': 'permitnum',
                 'applicant': 'contractor',
                 'applicant_city': 'originalcity',
                 'applicant_state': 'originalstate',
                 'applicant_zip': 'originalzip',
                 'address': 'originaladdress1',
                 'permit_type': 'permitclass',
                 'issue_date': 'issueddate',
                 'filed_date': 'applieddate',
                 'expiration_date': 'expiresdate',
                 'description': 'description'}},
     {'key': 'WA_WSDOT_Permits',
      'name': 'WSDOT Access & Utility Permits',
      'kind': 'unimplemented',
      'url': 'https://wsdot.wa.gov/business-wsdot/permits-applications',
      'reason': "WSDOT permits aren't published as a single public dataset"}]

